-- MySQL Script generated by MySQL Workbench
-- Fri Oct 18 05:18:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema integra
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `integra` ;

-- -----------------------------------------------------
-- Schema integra
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `integra` DEFAULT CHARACTER SET utf8 ;
USE `integra` ;

-- -----------------------------------------------------
-- Table `integra`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integra`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `integra`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(10) NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integra`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integra`.`tags` ;

CREATE TABLE IF NOT EXISTS `integra`.`tags` (
  `id_tag` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id_tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integra`.`publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integra`.`publicaciones` ;

CREATE TABLE IF NOT EXISTS `integra`.`publicaciones` (
  `id_publicacion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `titulo` TEXT NOT NULL,
  `contenido` TEXT NOT NULL,
  `aprovacion` INT NULL,
  `visitas` INT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id_publicacion`),
  INDEX `fk_publicacion_usuario_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_publicacion_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `integra`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integra`.`relaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integra`.`relaciones` ;

CREATE TABLE IF NOT EXISTS `integra`.`relaciones` (
  `id_relacion` INT NOT NULL AUTO_INCREMENT,
  `id_tag` INT NOT NULL,
  `id_publicacion` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id_relacion`),
  INDEX `fk_publicacion_idx` (`id_publicacion` ASC) ,
  INDEX `fk_relacion_tag_idx` (`id_tag` ASC) ,
  CONSTRAINT `fk_relacion_publicacion`
    FOREIGN KEY (`id_publicacion`)
    REFERENCES `integra`.`publicaciones` (`id_publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relacion_tag`
    FOREIGN KEY (`id_tag`)
    REFERENCES `integra`.`tags` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
